# Generated by Django 3.1.6 on 2022-03-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('serialnomor', models.CharField(max_length=30)),
                ('jenis_barang', models.CharField(choices=[('LCD', 'LCD'), ('Keyboard', 'Keyboard'), ('Battery', 'Battery'), ('HDD', 'HDD'), ('SSD', 'SSD'), ('RAM', 'RAM')], max_length=10)),
                ('harga_barang', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jasa', models.CharField(max_length=100)),
                ('harga_jasa', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_servis', models.CharField(max_length=15, null=True)),
                ('nama_barang_servis', models.CharField(max_length=100)),
                ('serial_nomor', models.CharField(max_length=30)),
                ('keluhan', models.TextField()),
                ('kelengkapan', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('status_servis', models.CharField(choices=[('Masuk', 'Masuk'), ('Dicek', 'Dicek'), ('Proses', 'Proses'), ('Selesai', 'Selesai'), ('Diambil', 'Diambil'), ('Batal', 'Batal')], default='Masuk', max_length=10)),
                ('tgl_masuk', models.DateField(auto_now_add=True)),
                ('tgl_keluar', models.DateField(auto_now=True, null=True)),
                ('id_plg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.pelanggan')),
            ],
            options={
                'ordering': ['-tgl_masuk'],
            },
        ),
        migrations.CreateModel(
            name='pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=15, null=True)),
                ('status_bayar', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=15)),
                ('total_bayar', models.IntegerField(default=0, null=True)),
                ('id_barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bs_admin.barang')),
                ('id_jasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bs_admin.jasa')),
                ('id_plg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.pelanggan')),
                ('id_servis', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bs_admin.servis')),
            ],
        ),
    ]
