# Generated by Django 3.1.6 on 2022-03-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_auto_20220315_2353'),
        ('bs_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bs_admin.barang'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='id_jasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bs_admin.jasa'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='id_plg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.pelanggan'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='id_servis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bs_admin.servis'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='id_plg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.pelanggan'),
        ),
    ]
