# Generated by Django 3.1.6 on 2022-03-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun_plg',
            name='level_user',
        ),
        migrations.RemoveField(
            model_name='akun_plg',
            name='plg',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='level_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='level_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='akun_bs',
        ),
        migrations.DeleteModel(
            name='akun_plg',
        ),
    ]
