# Generated by Django 3.1.6 on 2022-03-15 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_auto_20220313_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='level_user',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
